name: Build school-bot
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  markdown_lint:
    name: Build school-bot
    runs-on: ubuntu-latest
    steps:
      - name: Test report
        run: go test ./... -json > report.json
      - name: Report
        uses: becheran/go-testreport@main
        with:
          input: report.json
      - uses: actions/checkout@master
      - name: Golang linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
      - uses: actions/checkout@master
      - name: Send message to telegram
        if: success()
        env:
          STATUS_LINT: ☀️
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Finish build ${{ github.repository }} job status ${{ job.status }} ${{ env.STATUS_LINT }}
      - uses: actions/checkout@master
      - name: Send message to telegram
        if: failure()
        env:
          STATUS_LINT: ⚡️
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Finish build ${{ github.repository }} job status ${{ job.status }} ${{ env.STATUS_LINT }}
